### ISSUE TITLE
User Story 1 - Overview of Trips

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/my-trips#1]
## Value proposition

**As a** User
**I want to** see an overview of all my trips
**so that** I can quickly access my travel history and plans.

## Description

![Image](https://user-images.githubusercontent.com/128323709/268230117-ff9beb02-8463-4397-a29b-a1e5c945b318.svg)

## Acceptance criteria

- [ ] On the homepage there is a header with: "My Trips"
- [ ] There is a chronologically ordered list of the trips
- [ ] The list is vertically scrollable
- [ ] Each list item shows:
    - [ ] The country of the destination
    - [ ] The city of the destination
    - [ ] The starting date of the trip
    - [ ] The ending date of the trip
    - [ ] A custom picture

## Tasks

- [ ] Create the feature branch `feature/trip-list`
- [ ] Create database on MongoDB, 20 items in the collection trip-details
- [ ] Fetch a list of past, current, future trips from the database
- [ ] Implement the error handling logic to display an error message if there is an issue loading the list data from the database
- [ ] Create the component `Trip`, which renders:
    - [ ] The poster image of the trip
    - [ ] The name of the trip
    - [ ] The starting date of the trip
    - [ ] The ending date of the trip   
    - [ ] The city of the destination
    - [ ] The country of the destination
- [ ] Create the component `TripList`
- [ ] Map through the fetched list of trips and render a `Trip` component for each trip
- [ ] In the index.js:
    - [ ] Render a `<h1>` element "My Trips" 
    - [ ] Render the `TripList` component 

## Data Modell

```
Example Array:
[{ 
"title": "That belongs in a Museum",
"start date": "05.05.2023",
"ending date": "11.05.2023",
"city": "Tokyo",
"country": "Japan",
"image": "",  
}]
```

## MongoDB

`MongoDB: database: my-trips, collection: trip-details`

## Schema

```
const tripSchema = 
{
title: String (required), max characters: 20
start date: String (required),
ending date: String (required),
city: String (required),
country: String (required),
image: String (required) 
}
```
