### ISSUE TITLE
User Story 6 - Packing list Add

### ISSUE THREAD

**Issue by B-Baumeister** [miriam-ertl/my-trips#10]
## Value proposition

**As a** user
**I want to** create a packing list for a specific trip and add items to it
**so that** I can efficiently organize and plan my travel essentials for that particular journey

## Description

![Image](https://github.com/miriam-ertl/my-trips/assets/139886649/d0b2d2c5-f1f6-4303-83d1-5ed8e4ee4407)

## Acceptance criteria

- [x] On the detailspage: there is a button with `go to packing list` top right on the page 
- [x] By Clicking on this button the user is lead to the packing list section below the trip details 
- [x] By clicking on the add-button the user can add an item to the packing list
- [x] The new item will be are the first entry in the list
- [x] In this area is:
    - [x] A headline e.g.`Sakura packing list`
    - [x] A text box
    - [x] A button which says `add`
    - [x] Underneath is a list
- [x] An info if the list is empty 

## Tasks

- [x] Create a feature branch `feature/packing-list-Add`
- [x] Add a button `go to packing list` on `detailspage` for moving to packing list (below `edit trip`)
- [x] Add a Component `AddPackingList` with the function to add something to this list
    - [x] Additional inside this Component:
    - [x] Title is in headline
    - [x] A input field for tasks
    - [x] A `add` button to move the list-item to this package list as the first item in this list
- [x] Call this function in the lower part of the `detailspage`
- [x] An info for the user if there is no list entry 

## MongoDB

`MongoDB: database: my-trips, collection: trip-details`

## Schema

```
const tripSchema = 
{
title: String (required),
startDate: String (required),
endDate: String (required),
city: String (required),
country: String (required),
image: String (required), 
description: String (required),
packingList: [
    {name: String (required)},
    {isChecked: Boolean (true)}
]
}

**Comment by ahohnsen** [comment]
Hey there 👋 

Good job!

I suggest to rephrase the Value Proposition to be a bit more specific. 🙂 

_As a user
I want to create a packing list for a specific trip
so that I can efficiently organize and plan my travel essentials for that particular journey._

In the acceptance criteria you can focus a bit more on the possible user interactions instead of only describing what is visible in the UI. I suggest to add the following:

- By clicking on the add-button the user can add an item to the packing list

Where does the newly added item appear: on the top or bottom of the list? 
What happens if the user has no item on the packing list? Will there be a message indicating that the packing list is empty?

**Comment by ahohnsen** [comment]
Hi there,

Unfortunately, I do not see any updates in this user story. 🤔 

Please have a look again at your value proposition. The third part should mention the benefit for the user, not an action. You can look at my previous comment for inspiration.

In your acceptance criteria you only describe how the user can add a packing list to a trip. But you do not mention how a user can add an item to his packing list. I would add the following:


   - [ ] By clicking on the add-button the user can add an item to the packing list
  
Additionally, I suggest to specify the last point (_"An info if the list is empty"_} as you do not show it in your scribble. What kind of message the user will see when the packing list is empty?

**Comment by TobiasSteinhagen** [comment]
- [ ]  On the detailspage: there is a button with go to packing list top right on the page
Unfortunately, there is no button.

- [ ]  By Clicking on this button the user is lead to the packing list section below the trip details
Doesn't work, because there is no button 😅

- [ ]  The new item will be are the first entry in the list
The new item isn't the first on the list, it's the last.

✌️

**Comment by B-Baumeister** [comment]
alles erledigt =)
