### ISSUE TITLE
User Story 10  – Refactor One

### ISSUE THREAD

**Issue by B-Baumeister** [miriam-ertl/my-trips#13]
## Value proposition

**As a** web developer
**I want to** refactor the code
**so that** it is clean, maintainable and efficient.

## Description

- Refactoring the code

## Acceptance criteria

- [ ] The code is clean
- [ ] Needed components are implemented and prop-drilled

## Tasks

- [ ] Create a feature branch `feature/refactor-one`
- [ ] Add a clear selection of sources for images in the next.config.js
- [ ] Delete the CTA on the back-link on detailspage
- [ ] Sort the list items of the Overview page by date

**Comment by JessicaLoers** [comment]
**Hello Team 💚**
This User Story mixes **technical aspects** _code refactoring_ with **UX aspects** _optimal user journey_. 
It would ideally be better to deal with these aspects in separate user stories. 

_Refactoring_
**As a** web developer
**I want to** refactor the code
**so that** it is clean, maintainable and efficient.

**Description**
- Refactoring the code

**AC**
 - The code is clean
 - Needed components are implemented and prop-drilled
 
 **Tasks**
....

_User Journey_
**As a** user
**I want** to have an intuitive and seamless user experience
**so that I** can achieve my goals easily and efficiently.

**Description** 
- Implement missing features of the user stories 1 – 10.
➡️ Please list and link the features

**AC**
-  The character counter is shown within the text field
-  The wording of the CTAs gives clear advice how to act as a user

 **Tasks**
....

**Comment by JessicaLoers** [comment]
**You are good to go for the refactoring 👍**

**Comment by B-Baumeister** [comment]
Notiz: wo kommt der edit Button hin? wo kommt der delete button hin? (position im code und nicht auf der seite)

**Comment by JessicaLoers** [comment]
**Hey @B-Baumeister ✌️** 
ist das eine Notiz für euch, oder eine Frage an mich? 😁
