### ISSUE TITLE
User Story 11  – User experience

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/my-trips#15]
## Value proposition

**As a**  user
**I want to** have an intuitive and seamless user experience
**so that** I can achieve my goals easily and efficiently.

## Description

- [character counter of US 2](https://github.com/miriam-ertl/my-trips/issues/3)
- [chancel add trip wireframe of US 2](https://github.com/miriam-ertl/my-trips/issues/3)

## Acceptance criteria

- [ ] The character counter is shown within the text field
- [ ] The wording of the CTAs gives clear advice how to act as a user
- [ ] The back-link redirects to the overview page without any additional message

## Tasks

- [ ] Create the feature branch `feature/user-experience`
- [ ] Add a counter function to the text area field
- [ ] Check the wording on every CTA
- [ ] Delete the `ConfirmationMessage` on the back-link on the detailspage

**Comment by JessicaLoers** [comment]
yes ✨
