### ISSUE TITLE
User Story  12 – Packing list Complete

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/my-trips#16]
## Value proposition

**As a** user
**I want to** mark items on my packing list as packed 
**so that** I can keep track of what I've already prepared for my trip.

## Description

![Image](https://github.com/miriam-ertl/weather-and-activities-app/assets/128323709/ef1965f5-c1e3-41ae-b358-c7c2a9cae848)

## Acceptance criteria

- [ ] Each item in the packing list has one checkbox 
- [ ] This checkbox can be clicked when the item is packed 
- [ ] Clicking on a checkbox the item will be crossed out and it is marked as checked  
- [ ] Clicking on the checkbox again the item is unmarked

## Tasks

- [ ] Create the feature branch `feature/packing-list-Edit`
- [ ] Add a checkbox to each list item
- [ ] The checkbox has two values: checked and unchecked

**Comment by JessicaLoers** [comment]
**A very well-crafted User Story.**

_To some mustard there 🌭:_
The common design of a checkbox in many browsers is square. Modifying this design can be challenging, especially when aiming for a consistent look across various browsers. It's definitely doable, but might require extra work. 
In your wireframe, the checkbox is round. You don't necessarily have to use a square checkbox in your wireframes, but it's useful to be aware of the potential challenges in implementation.
