### ISSUE TITLE
User Story 2 - Details of a Trip

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/my-trips#2]
## Value proposition

**As a** User
**I want to** see the details of a certain trip
**so that** I can receive more information about this trip 

## Description

![Image](https://user-images.githubusercontent.com/139959429/268294623-ac3ff717-ea92-4156-818f-928eb4dbfa37.svg)

## Acceptance criteria

- [ ] Clicking on one trip item displays its details
- [ ] On the detailspage: there is a header with: `My Trips`
- [ ] Visible on the detailspage:
    - [ ] The poster image of the trip
    - [ ] The name of the trip
    - [ ] The starting date of the trip
    - [ ] The ending date of the trip
    - [ ] The city of the destination
    - [ ] The country of the destination
    - [ ] A description about the destination/etc. with the heading `My plans:`
- [ ] A back-button that leads to the list of trips  

## Tasks

- [ ] Create the feature branch `feature/detailspage`
- [ ] Create the trips' detailspage: `pages/trips/[id].js`
- [ ] Create the TripDetails component which renders: 
    - [ ]  The trips poster image
    - [ ]  The trips name
    - [ ]  The trips starting date
    - [ ]  The trips ending date
    - [ ]  The trips city
    - [ ]  The trips country 
    - [ ]  The trips description 
- [ ] Add a Link component which is wrapped around the `Trip` component to navigate to the corresponding detailspage         
- [ ] The detailspage also renders a `back-link` that leads to the homepage and a `<h1>` with the heading `My Trips`

**Comment by JessicaLoers** [comment]
**Really good job 🥳**
Just a picky comment:
- [ ] Each detailspage also renders a back-link that leads to the homepage and a <h1> with the heading My Trips
👉 _That's not quite right, because we only have one detailpage that renders something._
