### ISSUE TITLE
User Story 3  – Create a Trip

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/my-trips#3]
## Value proposition

**As a** user
**I want to** be able to create a new trip
**so that** I can easily plan my upcoming trips  

## Description

![Image](https://user-images.githubusercontent.com/139959429/268654510-e7d5be48-f880-47fb-8fe8-379489ac3cb0.png)

## Acceptance criteria

- [ ] Clicking on the `+ add trip` link on the homepage leads to a `form` page
- [ ] The `form` page consists of the following:
    - [ ] Heading of My Trips
    - [ ] Form
        - [ ] Title of the Trip: The field is required, and can contain a maximum of 30 characters
        - [ ] Starting date: The field is required, with a datepicker that fills the field after clicking on a date
        - [ ] Ending date: The field is required, with a datepicker that fills the field after clicking on a date
        - [ ] City: The field is required, and can contain a maximum of 30 characters
        - [ ] Country: The field is required, and can contain a maximum of 30 characters
        - [ ] Image (Url): The field is optional, without a maximum of characters
        - [ ] Description: The field is optional, with a maximum of 150 characters
    - [ ] An `add trip` button
    - [ ] A `cancel` link
    - [ ] A `back-link` arrow

_Note: When the maximum amount of characters for a form field hits its treshold, only the last character changes, and no new characters inputs are added._

- [ ] Clicking on the `cancel` link or the `back-link` will open a message below the form, which asks for the users next process steps either to continue or cancel adding a new trip 
 - [ ] If the user exits the clearance process by clicking on No, the message will disappear, the user can edit the last status of the form 
 - [ ] If the user exits the clearance process by clicking on Yes, the user will be lead to the homepage

- [ ] Clicking on the `add trip` button with all the required fields supplied will send the user to a new page, where the message: "Congratulations, you have a added a new trip" will be displayed. On this page there is a `home` link, that leads the user back to the homepage. This trip is now added to the list of trips on the homepage 
- [ ] Clicking on the `add trip` button while at least one required field is not supplied will inform the user about missing entries

## Tasks
- [ ] Create the feature branch `feature/addTrip`
- [ ] In `pages/api/trips/index.js`, write the `addTrip` function  with a `POST` request

#### Add a trip
- [ ] Create a component addForm
- [ ] Create inside this component a FormContainer
- [ ] Inside this FormContainer:
     - [ ] Create a label with the value _Title (max. 30 characters*)_
     - [ ] Create an input field for this label with the attribute required
     - [ ] Create a label with the value _Starting date (dd/mm/yyyy)*_ 
     - [ ] Create an input field for this label with the attribute required, type = date
     - [ ] Create a label with the value _Ending date (dd/mm/yyyy)*_ 
     - [ ] Create an input field for this Label with the attribute required, type = date
     - [ ] Create a label with the value _City (max. 30 characters) *_ 
     - [ ] Create a input field for this label with the attribute required
     - [ ] Create an label with the value _Country (max. 30 characters) *_ 
     - [ ] Create an input field for this label with the attribute required
     - [ ] Create a label with the value _Image (Url)_
     - [ ] Create an input field with placeholder _for example www.my-image.com_ for this label, with the attribute required
     - [ ] Create a label with the value Description (max. 150 characters) *
     - [ ] Create an input field for this label with the attribute required
     - [ ] Create a `submit button`

#### Submit `add trip`
- [ ] Create a new page `submitAddForm.js` 
- [ ] Create a text message on the page with a success message
- [ ] Clicking the Form `submit button` redirects to `submitAddForm.js`
- [ ] Submitting the forms sends the new trip information to the MongoDB database 

#### Cancel `add trip`
- [ ] Add a `CancelCreate` component that will be displayed below, triggered by an `onClick` event on either the `back-link` arrow or the `cancel` link
- [ ] The component renders the message: _Do you want to cancel adding a new trip? Clicking "Yes" will clear your input_. and the buttons/links _No_ and _Yes_ 
    - [ ] Clicking on the _Yes_ link leads to the homepage 
    - [ ] Clicking on the _No_ button hides the `CancelCreate` component     

#### First new trip
- [ ] Create a text message on the Homepage `index.js`, if no list item exists

#### Error message required form field
- [ ] Create an error message if not all required fields are filled and the form is already submitted

## API Endpoints status

| Method | URL               | What it does          |
|--------|-------------------|-----------------------|
| GET    | /api/trips     | Gets all trips     |
| GET    | /api/trips/:id | Gets trips by id    |
| POST   | /api/trips     | Creates new trip   |

**Comment by JessicaLoers** [comment]
You have almost defeated the beast. 🐲

It's super hard at first to name components and pages descriptively - that takes training and experience. 
**Here are my comments 🤓** 

**Submit add trip**
-  would change the name of the page to `addTripp.js`. Remember that this name will be part of the URL. 

**Cancel add trip**
- _CancelCreate_ component ➡️  Please think about the reusability of the component. For this reason, I would choose a generic name like `ConfirmationDialog` or `ConfirmationDialog` . 

You guys worked so hard on this user story - **that's why it's approved.**

**Comment by shrocket** [comment]
Hey! This looks really good! We (Tien and I) do have a couple of comments, though:
- In your acceptance criteria, you have written, "If the user exits the clearance process by clicking on No," but the buttons which appear are labeled "Yes" and "Continue." **There is no "No."** (I like "Continue" better anyway...)
- We don't know what "the clearance process" is, but it's not important to this QA. ;)
- The character counter in your description text area doesn't (yet) work (and we imagine you already know this).

Again, this looks really good! Congrats to you! 🚀
