### ISSUE TITLE
User Story 4 - Delete a Trip

### ISSUE THREAD

**Issue by DaveKrauss** [miriam-ertl/my-trips#4]
## Value proposition

**As a** User
**I want to** be able to delete a trip
**so that** I can focus easier on trips that are still relevant to me  

## Description

![Image](https://user-images.githubusercontent.com/128323709/268715657-79058770-774b-4f11-9f4b-ea13d0b491cc.svg)

## Acceptance criteria

- [ ]  On the detailspage there is a `delete button`
- [ ]  Clicking on the `delete button`  opens a small textbox
- [ ]  Content of textbox is:
    - [ ] "Do you really want to delete this trip?" 
    - [ ] A "Yes" and a "No" button 

- [ ] Clicking "Yes" will delete the trip and leads the user to the overview page 
- [ ] Clicking "No" will hide the textbox

## Tasks

- [ ] Create the feature branch `feature/deleteTrip`
- [ ] Add a `DeleteTrip` component that will be displayed below the button, triggered by an `onClick` event on the `delete` button. The component renders the message: "Do you want to delete this trip? Clicking "Yes" will delete your trip.", together with a "Yes" and "No" button. 
- [ ] Clicking "Yes" will delete the trip in the overview and the database and leads the user to the overview page.
- [ ] Clicking on the "No" button hides the `DeleteTrip` component

**Comment by JessicaLoers** [comment]
**Well done. ✌️**

I've some comments for you to think about. Nevertheless, this user story is approved.💚

**Acceptance Criteria**
➡️ **Addition:** What can be seen on the Overview Page when all entries are deleted? _Note: You don't need an additional wireframe for this - a written version is enough._

**Tasks**
-  Add a DeleteTrip component that will be displayed below the button, triggered by an onClick event on the delete button. The component renders the message: "Do you want to delete this trip? Clicking "Yes" will delete your trip.", together with a "Yes" and "No" button.
 Clicking "Yes" will delete the trip in the overview and the database and leads the user to the overview page.
⬇️
- This point is very detailed and basically just repeats the points of the AC. You are welcome to keep it a little shorter. 
-  Here you can reuse the `ConfirmationMessage` component from the following user story [User Story 3 – Create a Trip#3](https://github.com/miriam-ertl/my-trips/issues/3)
