### ISSUE TITLE
User Story 5 - Edit a Trip

### ISSUE THREAD

**Issue by StephanBergmann** [miriam-ertl/my-trips#5]
## Value proposition

**As a** User
**I want to** be able to edit a trip
**so that** I can change details of various trips in case I changed my mind 

## Description

![Image](https://user-images.githubusercontent.com/128323709/268720189-e587e104-306f-4dab-ba28-d5bd8522540a.svg)

## Acceptance criteria

- [ ] On the detailspage, there is an `edit` link with a button
- [ ] Clicking on this `edit` link leads to an `edit-trip` page, that shares the layout of the `form` page from US 3. The `+ add trip` button is replaced by an `edit trip` button and there is a `delete` button
- [ ] All the form fields of the `edit-trip` page are prefilled with the current trip details. The input values of the form fields can be altered
- [ ] Clicking on the `edit trip` button saves the current values of each form field to the trip and an alert with "changes applied" appears 
- [ ]  Clicking on the `delete` button opens a small textbox
- [ ]  Content of textbox is:
    - [ ] "Do you really want to delete this trip?" 
    - [ ] A "Yes" and a "No" button 

- [ ] Clicking "Yes" will delete the trip from the overview and the database and leads the user to the overview page 
- [ ] Clicking "No" will hide the textbox

## Tasks
- [ ] Create the feature branch `feature/editTrip`
- [ ] On the detailspage, add a `Link` component wrapped around  an `edit button`, that leads to the page `/api/edit-trip/:id`
- [ ] On the `edit-trip` page create a `EditTrip` component which renders a FormContainer with the current information of the trip in the input fields.
- [ ] Inside this FormContainer:
    - [ ] Create a label with the value Title (max. 30 characters*)
    - [ ] Create an input field for this label with the attribute required
    - [ ] Create a label with the value Starting date (dd/mm/yyyy)*
    - [ ] Create an input field for this label with the attribute required, type = date
    - [ ] Create a label with the value Ending date (dd/mm/yyyy)*
    - [ ] Create an input field for this Label with the attribute required, type = date
    - [ ] Create a label with the value City (max. 30 characters) *
    - [ ] Create a input field for this label with the attribute required
    - [ ] Create an label with the value Country (max. 30 characters) *
    - [ ] Create an input field for this label with the attribute required
    - [ ] Create a label with the value Image (Url)
    - [ ] Create an input field with the attribute required
    - [ ] Create a label with the value Description (max. 150 characters) *
    - [ ] Create an input field for this label with the attribute required
    - [ ] Create a submit button
- [ ] Create a cancel button
- [ ] Create a delete button

#### Cancel button
- [ ] Add a `ConfirmationMessage` component that will be displayed below, triggered by an `onClick` event on either the `back-link` arrow or the `cancel` Link
- [ ] The component renders the message "Do you want to cancel editing this trip? Clicking "Yes" will clear your input." 
The component also renders a `Link` component wrapped around the two buttons: "No" and "Yes" 
    - [ ] Clicking on the "Yes" `Link` leads to the overview page 
    - [ ] Clicking on the "No" `Link` hides the `CancelCreate` component     

#### Delete button
- [ ] Add a `DeleteTrip` component that will be displayed below the button, triggered by an `onClick` event on the `delete` button. The component renders the message "Do you want to delete this trip? Clicking "Yes" will delete your trip."
The component also renders a `Link` component wrapped around the two buttons: "No" and "Yes"  
    - [ ] Clicking on the "Yes" `Link` will delete the trip in the overview and the database and leads the user to the overview page
    - [ ] Clicking on the "No" `Link` hides the `DeleteTrip` component 

## API Endpoints status

| Method | URL               | What it does          |
|--------|-------------------|-----------------------|
| GET    | /api/trips     | Gets all trips     |
| GET    | /api/trips/:id | Gets trips by id    |
| POST   | /api/trips     | Creates new trip   |
| PUT    | /api/edit-trip/:id | Edits trips by id   |

**Comment by Charlotte-Ketteler** [comment]
This truly is a very detailed and well documented US! Well done!

**Comment by ohlunlacassi** [comment]
Well done, but there is something you can change a bit. 

When i clicked change the starting and the end date, it is changed to another format. 

And then below the form, there're two buttons "cancel" and "delete trip". When i clicked the cancel button, there's a confirmation message that i have to should either "yes" or "continue". That's a bit confusing.

The confirmation text of the delete button doesn't match to acceptance criteria.

**Comment by miriam-ertl** [comment]
The Normalization of the date structure is sheduled for an upcoming User Story 10 (refactoring one).

The wording is of the cancel-button match and especially the delete-button match now announced wording in US5.

**Comment by Pia-Lueling** [comment]
hello :)

my first review alone, so don't be too hard on me ;)

I found a few little things: When I go to the add trip link, why are the dates (start and end date) that I entered as a user no longer displayed? So I have to enter the data again? if they have not changed.
Why is there a cancel and delete button here? I was confused at first because the delete button is already on the details page!
Unfortunately, if I click on delete and then on yes, it doesn't delete the trip.

Otherwise everything looks really good :)

**Comment by miriam-ertl** [comment]
Thank you Pia very much, 
we read your remarks closely. 

We fixed and sheduled some issues for upcoming US: 

- [x] "Unfortunately, if I click on delete and then on yes, it doesn't delete the trip."
Now Clicking yes leads to Overview Page and deletes the Trip at the same time.

- [x] "When I go to the add trip link, why are the dates (start and end date) that I entered as a user no longer displayed? So I have to enter the data again? if they have not changed." Right, we sheduled this issue see AC (=> the dates of the older trips aren't displayed, this problem will be solved in US11)

"Why is there a cancel and delete button here? I was confused at first because the delete button is already on the details page!" While editing a Trip a user might realize the whole Trip planning is getting nonsense and then the user is able to delete the Trip immediately without clicking back on the overview.

**Comment by TienPham18** [comment]
This looks wonderful as it is described in the Acceptance Criteria 🚀.

There is only one question I was wondering: when I click on the `Edit trip` on the details page, which directs me to the editForm. So I saw the `delete` button appearing both in details page and editForm page. Are you aware of that as your intention to put in both pages?
